"""Tests for vig_utils.check_pr_agent_fingerprints."""

from pathlib import Path
from unittest.mock import patch

import pytest
from vig_utils import check_pr_agent_fingerprints
from vig_utils.utils import (
    agent_blocklist_path,
    contains_agent_fingerprint,
    load_blocklist,
)


class TestCanonicalBlocklist:
    """Guard the org 'never name an AI in history' control against regressions.

    The canonical ``.github/agent-blocklist.toml`` must keep rejecting BOTH the
    legacy ``cursor`` identity and the current ``claude`` identity. These tests
    exercise the real blocklist file (not a mock) so dropping either ``names``
    entry — e.g. while removing the Cursor toolchain — fails CI.
    """

    @pytest.fixture
    def blocklist(self) -> dict:
        path = agent_blocklist_path(start=Path(__file__))
        assert path.exists(), f"canonical blocklist missing at {path}"
        return load_blocklist(path)

    @pytest.mark.parametrize("identity", ["cursor", "claude"])
    def test_identity_blocked_in_commit_message(self, blocklist, identity):
        content = f"feat: add thing\n\nGenerated by {identity.capitalize()}"
        assert contains_agent_fingerprint(content, blocklist) == identity

    def test_canonical_blocklist_lists_cursor_and_claude(self, blocklist):
        assert "cursor" in blocklist["names"]
        assert "claude" in blocklist["names"]


# Verbatim 1.10.0 CHANGELOG wording for #1503, before commit 2c533424 reworded
# it to unblock the release train (Refs: #1516). prepare-release renders the
# CHANGELOG section into the release PR body, so this text is what the check saw.
HISTORICAL_1503_ENTRY = (
    "  - `promote-release.yml`'s `reset-sync-mirror` embedded the Commit App "
    "token\n"
    "    in the push URL, but `actions/checkout` persists its own credentials "
    "as\n"
    "    `http.<host>.extraheader`, which outranks URL userinfo. The "
    "force-push\n"
    "    therefore ran as `github-actions[bot]` under `contents: read` and "
    "failed\n"
    "    with a 403 on every mirror-mode consumer — after the release was "
    "already\n"
    "    published, so the red run misrepresented an otherwise healthy "
    "promote.\n"
    "    The job now generates the App token *before* checkout and checks out "
    "with\n"
    "    it, and `contents: read` stays deliberately in place\n"
)


class TestDescriptiveIdentityMentions:
    """A PR body that *describes* a bot-identity bug must not fail the check.

    Refs: #1521 (follow-up to the #1516 release-train blocker). These tests run
    against the real ``.github/agent-blocklist.toml`` so they encode the gate as
    CI actually enforces it.
    """

    @pytest.fixture
    def blocklist_path(self) -> Path:
        path = agent_blocklist_path(start=Path(__file__))
        assert path.exists(), f"canonical blocklist missing at {path}"
        return path

    def _run(self, blocklist_path: Path, title: str, body: str) -> int:
        with (
            patch.dict("os.environ", {"PR_TITLE": title, "PR_BODY": body}, clear=True),
            patch(
                "vig_utils.check_pr_agent_fingerprints.agent_blocklist_path",
                return_value=blocklist_path,
            ),
        ):
            return check_pr_agent_fingerprints.main()

    def test_release_pr_body_describing_bot_identity_bug_passes(self, blocklist_path):
        assert (
            self._run(
                blocklist_path,
                "release: 1.10.0",
                f"## [1.10.0]\n\n### Fixed\n\n{HISTORICAL_1503_ENTRY}",
            )
            == 0
        )

    def test_real_attribution_trailer_still_fails(self, blocklist_path):
        assert (
            self._run(
                blocklist_path,
                "feat: add thing",
                "Co-authored-by: Agent <cursoragent@cursor.com>",
            )
            == 1
        )

    def test_bot_identity_author_line_still_fails(self, blocklist_path):
        assert (
            self._run(
                blocklist_path,
                "chore: sync mirror",
                "Author: GitHub Actions <github-actions[bot]@users.noreply.github.com>",
            )
            == 1
        )


class TestMain:
    """Tests for main entrypoint."""

    def test_returns_zero_when_blocklist_missing(self, tmp_path):
        missing = tmp_path / "missing.toml"
        with (
            patch.dict(
                "os.environ", {"PR_TITLE": "title", "PR_BODY": "body"}, clear=True
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.agent_blocklist_path",
                return_value=missing,
            ),
        ):
            assert check_pr_agent_fingerprints.main() == 0

    def test_returns_one_when_fingerprint_found(self, tmp_path, capsys):
        blocklist_file = tmp_path / "agent-blocklist.toml"
        blocklist_file.write_text("[patterns]\n")
        blocklist = {"names": ["cursor"], "emails": [], "trailers": []}

        with (
            patch.dict(
                "os.environ",
                {"PR_TITLE": "feat: update", "PR_BODY": "Authored by Cursor"},
                clear=True,
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.agent_blocklist_path",
                return_value=blocklist_file,
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.load_blocklist",
                return_value=blocklist,
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.contains_agent_fingerprint",
                return_value="cursor",
            ),
        ):
            result = check_pr_agent_fingerprints.main()

        captured = capsys.readouterr()
        assert result == 1
        assert "blocked AI agent fingerprint" in captured.err

    def test_returns_zero_when_no_fingerprint(self, tmp_path):
        blocklist_file = tmp_path / "agent-blocklist.toml"
        blocklist_file.write_text("[patterns]\n")
        blocklist = {"names": ["cursor"], "emails": [], "trailers": []}

        with (
            patch.dict(
                "os.environ",
                {"PR_TITLE": "fix: adjust parser", "PR_BODY": "Refs: #217"},
                clear=True,
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.agent_blocklist_path",
                return_value=blocklist_file,
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.load_blocklist",
                return_value=blocklist,
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.contains_agent_fingerprint",
                return_value=None,
            ),
        ):
            assert check_pr_agent_fingerprints.main() == 0

    def test_handles_empty_title_and_body(self, tmp_path):
        blocklist_file = tmp_path / "agent-blocklist.toml"
        blocklist_file.write_text("[patterns]\n")
        blocklist = {"names": ["cursor"], "emails": [], "trailers": []}

        with (
            patch.dict("os.environ", {}, clear=True),
            patch(
                "vig_utils.check_pr_agent_fingerprints.agent_blocklist_path",
                return_value=blocklist_file,
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.load_blocklist",
                return_value=blocklist,
            ),
            patch(
                "vig_utils.check_pr_agent_fingerprints.contains_agent_fingerprint",
                return_value=None,
            ) as mock_contains,
        ):
            assert check_pr_agent_fingerprints.main() == 0

        mock_contains.assert_called_once_with("\n", blocklist)
